config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'up' => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboard#index"
  get '/', to: 'dashboard#index', as: 'dashboard_index'
  get '/dashboard', to: 'dashboard#show', as: 'dashboard_details'
  get '/overview', to: 'dashboard#overview', as: 'dashboard_overview'
  get '/welcome', to: 'home#welcome', as: 'welcome'
  get '/privacy', to: 'home#privacy', as: 'privacy'
  get '/permissions', to: 'home#permissions', as: 'permissions'
  get '/data', to: 'home#data', as: 'data'
  get '/account_deletion', to: 'home#account_deletion', as: 'account_deletion'

  resources :sessions, only: %i[new create destroy]
  resources :users
  resources :challenges, only: %w[index show] do
    get :ended, on: :collection
    resources :challenge_users, only: %w[index new create destroy]
    resources :teams, only: %w[index new create] do
      resources :team_challenge_users, only: %w[create]
    end
  end
  resources :notifications, only: %w[index] do
    put :read_all, on: :collection
  end

  resources :configurations, only: [] do
    get :ios, on: :collection
    get :android, on: :collection
  end

  resources :settings

  resources :tournaments
  resources :tournament_participants

  resources :goals, only: %w[index new create edit update]

  namespace :api, defaults: { format: 'json' }, path: '/api' do
    resources :activities, only: [:create]
    put '/users', to: 'users#update'
  end

  match '*unmatched_route', to: redirect('/404.html'), via: :all
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_encoded_token, only: :show

  def index; end

  def show
    @active_tournament = current_user.active_tournament
    @daily_steps = Overview::ActivitiesThisMonthQuery.call(params[:date])
                                                         .group_by_day(:date, format: "%d")
                                                         .sum(:steps)
    @daily_heart_rate = {}
    [:heart_rate, :max_heart_rate].each { |type|
      @daily_heart_rate[type] = MaxHeartRatePerDay.call(type, params[:date])
    }

    @steps_this_month = Overview::ActivitiesThisMonthQuery.call(params[:date]).sum(:steps)
    @steps_last_month = Overview::ActivitiesLastMonthQuery.call.sum(:steps)
    @distance_this_month = Overview::ActivitiesThisMonthQuery.call(params[:date]).sum(:distance)
    @calories_this_month = Overview::ActivitiesThisMonthQuery.call(params[:date]).sum(:calories)
    @activities_this_month = Overview::ActivitiesThisMonthQuery.call(params[:date]).order(:date)
  end

  def overview
    @top_20_steps = Top20StepsQuery.call
  end

  private

  def set_encoded_token
    expires_at = Time.zone.now.to_i + 1.hour.to_i
    payload = { user_id: current_user.id, exp: expires_at }

    @encoded_token = JWT.encode(payload, Rails.application.credentials.secret_key_base, 'HS256')
  end
end

app/views/dashboard/_loading_skeleton.html.erb
<div role="status" class="max-w-md p-4 space-y-4 border border-gray-200 divide-y divide-gray-200 rounded shadow animate-pulse dark:divide-gray-700 md:p-6 dark:border-gray-700">
  <div class="flex items-center justify-between">
    <div>
      <div class="h-2.5 bg-gray-300 rounded-full dark:bg-gray-600 w-24 mb-2.5"></div>
      <div class="w-32 h-2 bg-gray-200 rounded-full dark:bg-gray-700"></div>
    </div>
    <div class="h-2.5 bg-gray-300 rounded-full dark:bg-gray-700 w-12"></div>
  </div>
  <div class="flex items-center justify-between pt-4">
    <div>
      <div class="h-2.5 bg-gray-300 rounded-full dark:bg-gray-600 w-24 mb-2.5"></div>
      <div class="w-32 h-2 bg-gray-200 rounded-full dark:bg-gray-700"></div>
    </div>
    <div class="h-2.5 bg-gray-300 rounded-full dark:bg-gray-700 w-12"></div>
  </div>
  <div class="flex items-center justify-between pt-4">
    <div>
      <div class="h-2.5 bg-gray-300 rounded-full dark:bg-gray-600 w-24 mb-2.5"></div>
      <div class="w-32 h-2 bg-gray-200 rounded-full dark:bg-gray-700"></div>
    </div>
    <div class="h-2.5 bg-gray-300 rounded-full dark:bg-gray-700 w-12"></div>
  </div>
  <div class="flex items-center justify-between pt-4">
    <div>
      <div class="h-2.5 bg-gray-300 rounded-full dark:bg-gray-600 w-24 mb-2.5"></div>
      <div class="w-32 h-2 bg-gray-200 rounded-full dark:bg-gray-700"></div>
    </div>
    <div class="h-2.5 bg-gray-300 rounded-full dark:bg-gray-700 w-12"></div>
  </div>
  <div class="flex items-center justify-between pt-4">
    <div>
      <div class="h-2.5 bg-gray-300 rounded-full dark:bg-gray-600 w-24 mb-2.5"></div>
      <div class="w-32 h-2 bg-gray-200 rounded-full dark:bg-gray-700"></div>
    </div>
    <div class="h-2.5 bg-gray-300 rounded-full dark:bg-gray-700 w-12"></div>
  </div>
  <span class="sr-only">Loading...</span>
</div>

<div role="status" class="max-w-sm p-4 border border-gray-200 rounded shadow animate-pulse md:p-6 dark:border-gray-700 mt-3">
  <div class="h-2.5 bg-gray-200 rounded-full dark:bg-gray-700 w-32 mb-2.5"></div>
  <div class="w-48 h-2 mb-10 bg-gray-200 rounded-full dark:bg-gray-700"></div>
  <div class="flex items-baseline mt-4">
    <div class="w-full bg-gray-200 rounded-t-lg h-72 dark:bg-gray-700"></div>
    <div class="w-full h-56 ms-6 bg-gray-200 rounded-t-lg dark:bg-gray-700"></div>
    <div class="w-full bg-gray-200 rounded-t-lg h-72 ms-6 dark:bg-gray-700"></div>
    <div class="w-full h-64 ms-6 bg-gray-200 rounded-t-lg dark:bg-gray-700"></div>
    <div class="w-full bg-gray-200 rounded-t-lg h-80 ms-6 dark:bg-gray-700"></div>
    <div class="w-full bg-gray-200 rounded-t-lg h-72 ms-6 dark:bg-gray-700"></div>
    <div class="w-full bg-gray-200 rounded-t-lg h-80 ms-6 dark:bg-gray-700"></div>
  </div>
  <span class="sr-only">Loading...</span>
</div>

app/views/dashboard/_summary_value.html.erb
<% percentage_change = percentage_change(value, last_value) %>
<% color = value_color(percentage_change) %>

<span class="rtl:ml-1.5 flex rtl:flex-row-reverse font-normal items-center mr-1.5 text-sm <%= color %> dark:<%= color %>">
  <%= arrow_icon(value - last_value) %>
  <% if ltr? %>
    <%= percentage_change %>%
  <% elsif rtl? %>
    <span>%</span><span><%= percentage_change %></span>
  <% end %>
</span>

app/views/dashboard/index.html.erb
<% if turbo_native_app? %>
  <%= turbo_stream_from("activities_turbo_native_user_#{current_user.id}") %>
<% end %>

<div id="dashboard-details">
  <%= turbo_frame_tag(:dashboard, src: dashboard_details_path(date: params[:date])) do %>
    <%= render 'loading_skeleton' %>
  <% end %>
</div>

<%= render 'layouts/footer' %>

app/views/dashboard/overview.html.erb
<%= turbo_frame_tag :dashboard do %>
  <%= render 'layouts/navigation' %>
  <%= render 'dashboard/partials/bridge' %>

  <% cache current_user do %>
    <div class="flex overflow-hidden bg-gray-50 dark:bg-gray-900" data-navigation-target="overviewFrame">
      <div id="main-content" class="relative w-full max-w-screen-2xl mx-auto h-full overflow-y-auto bg-gray-50 dark:bg-gray-900">
        <main>
          <div class="px-4 pt-6 2xl:px-0">
            <p class="font-light font-semibold text-center text-gray-500 dark:text-gray-400"><%= l(current_user.created_at.to_date, format: :month_year) %> - <%= t('.today') %></p>

            <div class="grid w-full grid-cols-1 gap-4 mt-4 xl:grid-cols-3 2xl:grid-cols-3">

              <div class="items-center justify-between p-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:flex dark:border-gray-700 sm:p-6 dark:bg-gray-800">
                <div class="w-full">
                  <h3 class="text-base font-normal text-gray-500 dark:text-gray-400"><%= t('.steps') %></h3>
                  <span class="text-2xl font-bold leading-none text-gray-900 sm:text-3xl dark:text-white"><%= number_with_delimiter(current_user.activities.sum(:steps)) %></span>
                </div>
              </div>
            </div>

            <div class="grid w-full grid-cols-2 gap-4 mt-4 xl:grid-cols-3 2xl:grid-cols-3">
              <div class="items-center justify-between p-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:flex dark:border-gray-700 sm:p-6 dark:bg-gray-800">
                <div class="w-full">
                  <h3 class="text-base font-normal text-gray-500 dark:text-gray-400"><%= t('.distance') %></h3>
                  <span class="text-2xl font-bold leading-none text-gray-900 sm:text-3xl dark:text-white"><%= number_with_delimiter(format_distance(current_user.activities.sum(:distance))) %></span>
                </div>
              </div>
              <div class="items-center justify-between p-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:flex dark:border-gray-700 sm:p-6 dark:bg-gray-800">
                <div class="w-full">
                  <h3 class="text-base font-normal text-gray-500 dark:text-gray-400"><%= t('.calories') %></h3>
                  <span class="text-2xl font-bold leading-none text-gray-900 sm:text-3xl dark:text-white"><%= number_with_delimiter(current_user.activities.sum(:calories).to_i) %></span>
                </div>
              </div>
            </div>

            <div class="grid w-full grid-cols-1 gap-4 mt-4 xl:grid-cols-1 2xl:grid-cols-1">
              <div class="p-4 mb-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:p-6 dark:border-gray-700 dark:bg-gray-800 xl:mb-0">
                <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-4"><%= t('.steps_per_year_chart_title') %></h3>

                <div class="w-full">
                  <%= line_chart TotalStepsPerYear.call %>
                </div>
              </div>
            </div>

            <div class="grid w-full grid-cols-1 gap-4 mt-4 xl:grid-cols-1 2xl:grid-cols-1">
              <div class="p-4 mb-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:p-6 dark:border-gray-700 dark:bg-gray-800 xl:mb-0">
                <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-4"><%= t('.steps_per_month_chart_title') %></h3>

                <div class="w-full">
                  <%= line_chart TotalStepsPerMonth.call %>
                </div>
              </div>
            </div>

            <div class="grid w-full grid-cols-1 gap-4 mt-4 xl:grid-cols-1 2xl:grid-cols-1">
              <div class="p-4 mb-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:p-6 dark:border-gray-700 dark:bg-gray-800 xl:mb-0">
                <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-4"><%= t('.heart_rate_per_month_chart_title') %></h3>

                <div class="w-full">
                  <%= line_chart [:heart_rate, :max_heart_rate].map { |type|
                    { name: t(".#{type}"), data: MaxHeartRatePerMonth.call(type) }
                  } %>
                </div>
              </div>
            </div>

            <div class="grid w-full grid-cols-1 gap-4 mt-4 xl:grid-cols-1 2xl:grid-cols-1">
              <div class="p-4 bg-white border border-gray-200 rounded-lg shadow-sm dark:border-gray-700 sm:p-6 dark:bg-gray-800">
                <h3 class="flex items-center mb-4 text-lg font-semibold text-gray-900 dark:text-white"><%= t('.top_twenty') %></h3>
                <div id="fullWidthTabContent" class="border-t border-gray-200 dark:border-gray-600">
                  <div class="pt-4" id="faq" role="tabpanel" aria-labelledby="faq-tab">
                    <ul role="list" class="divide-y divide-gray-200 dark:divide-gray-700">
                      <% @top_20_steps.each do |record| %>
                        <li class="py-3 sm:py-4">
                          <div class="flex items-center justify-between">
                            <div class="flex items-center min-w-0">
                              <div class="ml-3">
                                <p class="font-medium text-gray-900 truncate dark:text-white">
                                  <%= l(record.date, format: :long) %>
                                </p>
                              </div>
                            </div>
                            <div class="inline-flex items-center text-base font-semibold dark:text-white">
                              <%= record.steps %>
                            </div>
                          </div>
                        </li>
                      <% end %>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </main>
      </div>
    </div>
  <% end %>
<% end %>

app/views/dashboard/show.html.erb
<% content_for :title, Date.current.strftime('%B') %>

<%= turbo_frame_tag :dashboard do %>
  <%= render 'layouts/navigation' %>

  <% if new_update_available? %>
    <%= render 'dashboard/partials/new_update_available' %>
  <% end %>

  <main data-navigation-target="thisMonthFrame">
    <div class="px-4 pt-6 2xl:px-0">
      <%= render 'dashboard/partials/bridge' %>
      <%= render 'dashboard/partials/last_sync' %>

      <div class="flex items-center justify-center mr-1.5 dark:text-gray-500 mb-2 mt-2">
        <% if current_user.created_at <= date_from_params(params[:date]).prev_month %>
          <kbd class="rtl:rotate-180 inline-flex items-center px-2 py-1.5 text-gray-800 bg-gray-100 border border-gray-200 rounded-lg dark:bg-gray-600 dark:text-gray-100 dark:border-gray-500">
            <%= link_to dashboard_details_path(date: date_from_params(params[:date]).prev_month.strftime('%Y-%m')), 'data-turbo-action': 'replace' do %>
              <svg class="w-2.5 h-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 10 16">
                <path d="M8.766.566A2 2 0 0 0 6.586 1L1 6.586a2 2 0 0 0 0 2.828L6.586 15A2 2 0 0 0 10 13.586V2.414A2 2 0 0 0 8.766.566Z"/>
              </svg>
              <span class="sr-only">Arrow key left</span>
            <% end %>
          </kbd>
        <% end %>

        <% if current_user.created_at.next_month <= Date.current %>
          <span class="mx-2"> <%= l(date_from_params(params[:date]), format: :month_year) %></span>
        <% end %>

        <% if Date.current >= date_from_params(params[:date]).next_month %>
          <kbd class="rtl:rotate-180 inline-flex items-center px-2 py-1.5 text-gray-800 bg-gray-100 border border-gray-200 rounded-lg dark:bg-gray-600 dark:text-gray-100 dark:border-gray-500">
            <%= link_to dashboard_details_path(date: date_from_params(params[:date]).next_month.strftime('%Y-%m')), 'data-turbo-action': 'replace' do %>
              <svg class="w-2.5 h-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 10 16">
                <path d="M3.414 1A2 2 0 0 0 0 2.414v11.172A2 2 0 0 0 3.414 15L9 9.414a2 2 0 0 0 0-2.828L3.414 1Z"/>
              </svg>
              <span class="sr-only">Arrow key right</span>
            <% end %>
          </kbd>
        <% end %>
      </div>

      <% if @active_tournament && !params[:date] %>
        <%= link_to tournament_path(@active_tournament), data: { turbo_frame: '_top' } do %>
          <%= render 'dashboard/partials/active_tournament_card', active_tournament: @active_tournament %>
        <% end %>
      <% end %>

      <% cache "#{current_user.updated_at.iso8601}_#{params[:date]}" do %>
        <%= render 'dashboard/partials/summary' %>
        <%= render 'dashboard/partials/daily_steps' %>
        <%= render 'dashboard/partials/daily_heart_rate' %>
        <%= render 'dashboard/partials/activities_table' %>
      <% end %>
    </div>
  </main>
<% end %>

app/views/dashboard/summary.html.erb
<%= turbo_frame_tag :dashboard do %>
  <div data-controller="navigation">
    <%= render 'dashboard/partials/navigation' %>

    <div class="flex overflow-hidden bg-gray-50 dark:bg-gray-900" data-navigation-target="summaryFrame">
      <div id="main-content" class="relative w-full max-w-screen-2xl mx-auto h-full overflow-y-auto bg-gray-50 dark:bg-gray-900">
        <main>
          <div class="px-4 pt-6 2xl:px-0">
            <%= render 'dashboard/partials/bridge' %>

            <div class="grid w-full grid-cols-1 gap-4 mt-4 xl:grid-cols-3 2xl:grid-cols-3">

              <div class="items-center justify-between p-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:flex dark:border-gray-700 sm:p-6 dark:bg-gray-800">
                <div class="w-full">
                  <h3 class="text-base font-normal text-gray-500 dark:text-gray-400">Steps</h3>
                  <span class="text-2xl font-bold leading-none text-gray-900 sm:text-3xl dark:text-white"><%= current_user.activities.sum(:steps) %></span>
                </div>
              </div>
              <div class="items-center justify-between p-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:flex dark:border-gray-700 sm:p-6 dark:bg-gray-800">
                <div class="w-full">
                  <h3 class="text-base font-normal text-gray-500 dark:text-gray-400">Distance (KM)</h3>
                  <span class="text-2xl font-bold leading-none text-gray-900 sm:text-3xl dark:text-white"><%= format_distance(current_user.activities.sum(:distance)) %></span>
                </div>
              </div>
              <div class="items-center justify-between p-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:flex dark:border-gray-700 sm:p-6 dark:bg-gray-800">
                <div class="w-full">
                  <h3 class="text-base font-normal text-gray-500 dark:text-gray-400">Calories (kcal)</h3>
                  <span class="text-2xl font-bold leading-none text-gray-900 sm:text-3xl dark:text-white"><%= current_user.activities.sum(:calories).to_i %></span>
                </div>
              </div>
            </div>

            <div class="grid w-full grid-cols-1 gap-4 mt-4 xl:grid-cols-1 2xl:grid-cols-1">
              <div class="p-4 mb-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:p-6 dark:border-gray-700 dark:bg-gray-800 xl:mb-0">
                <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-4">Steps per year</h3>

                <div class="w-full">
                  <%= line_chart TotalStepsPerYear.call %>
                </div>
              </div>
            </div>

            <div class="grid w-full grid-cols-1 gap-4 mt-4 xl:grid-cols-1 2xl:grid-cols-1">
              <div class="p-4 mb-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:p-6 dark:border-gray-700 dark:bg-gray-800 xl:mb-0">
                <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-4">Accumulated Steps</h3>

                <div class="w-full">
                  <%= line_chart StepsAccumulatedSumQuery.call %>
                </div>
              </div>
            </div>

            <div class="grid w-full grid-cols-1 gap-4 mt-4 xl:grid-cols-1 2xl:grid-cols-1">
              <div class="p-4 mb-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:p-6 dark:border-gray-700 dark:bg-gray-800 xl:mb-0">
                <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-4">Steps per month</h3>

                <div class="w-full">
                  <%= line_chart TotalStepsPerMonth.call %>
                </div>
              </div>
            </div>

            <div class="grid w-full grid-cols-1 gap-4 mt-4 xl:grid-cols-1 2xl:grid-cols-1">
              <div class="p-4 mb-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:p-6 dark:border-gray-700 dark:bg-gray-800 xl:mb-0">
                <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-4">Steps per month/year</h3>

                <div class="w-full">
                  <%= line_chart TotalStepsPerMonthYear.call %>
                </div>
              </div>
            </div>

            <div class="grid w-full grid-cols-1 gap-4 mt-4 xl:grid-cols-1 2xl:grid-cols-1">
              <div class="p-4 mb-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:p-6 dark:border-gray-700 dark:bg-gray-800 xl:mb-0">
                <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-4">Heart Rate</h3>

                <div class="w-full">
                  <%= line_chart [:heart_rate, :max_heart_rate].map { |type|
                    { name: type, data: MaxHeartRatePerMonth.call(type) }
                  } %>
                </div>
              </div>
            </div>

            <div class="grid w-full grid-cols-1 gap-4 mt-4 xl:grid-cols-1 2xl:grid-cols-1">
              <div class="p-4 bg-white border border-gray-200 rounded-lg shadow-sm dark:border-gray-700 sm:p-6 dark:bg-gray-800">
                <h3 class="flex items-center mb-4 text-lg font-semibold text-gray-900 dark:text-white">Top 20 activities</h3>
                <div id="fullWidthTabContent" class="border-t border-gray-200 dark:border-gray-600">
                  <div class="pt-4" id="faq" role="tabpanel" aria-labelledby="faq-tab">
                    <ul role="list" class="divide-y divide-gray-200 dark:divide-gray-700">
                      <% @top_20_steps.each do |record| %>
                        <li class="py-3 sm:py-4">
                          <div class="flex items-center justify-between">
                            <div class="flex items-center min-w-0">
                              <div class="ml-3">
                                <p class="font-medium text-gray-900 truncate dark:text-white">
                                  <%= l(record.date, format: :long) %>
                                </p>
                              </div>
                            </div>
                            <div class="inline-flex items-center text-base font-semibold dark:text-white">
                              <%= record.steps %>
                            </div>
                          </div>
                        </li>
                      <% end %>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </main>
      </div>
    </div>
  </div>
<% end %>