config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'up' => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboard#index"
  get '/', to: 'dashboard#index', as: 'dashboard_index'
  get '/dashboard', to: 'dashboard#show', as: 'dashboard_details'
  get '/overview', to: 'dashboard#overview', as: 'dashboard_overview'
  get '/welcome', to: 'home#welcome', as: 'welcome'
  get '/privacy', to: 'home#privacy', as: 'privacy'
  get '/permissions', to: 'home#permissions', as: 'permissions'
  get '/data', to: 'home#data', as: 'data'
  get '/account_deletion', to: 'home#account_deletion', as: 'account_deletion'

  resources :sessions, only: %i[new create destroy]
  resources :users
  resources :challenges, only: %w[index show] do
    get :ended, on: :collection
    resources :challenge_users, only: %w[index new create destroy]
    resources :teams, only: %w[index new create] do
      resources :team_challenge_users, only: %w[create]
    end
  end
  resources :notifications, only: %w[index] do
    put :read_all, on: :collection
  end

  resources :configurations, only: [] do
    get :ios, on: :collection
    get :android, on: :collection
  end

  resources :settings

  resources :tournaments
  resources :tournament_participants

  resources :goals, only: %w[index new create edit update]

  namespace :api, defaults: { format: 'json' }, path: '/api' do
    resources :activities, only: [:create]
    put '/users', to: 'users#update'
  end

  match '*unmatched_route', to: redirect('/404.html'), via: :all
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :activities, dependent: :destroy

  has_many :tournament_participants, dependent: :destroy
  has_many :challenge_users, dependent: :destroy
  has_many :challenges, through: :challenge_users
  has_many :notifications, dependent: :destroy
  has_many :goals, dependent: :destroy

  scope :with_notification_token, -> { where.not(notification_token: nil) }

  validates :email, presence: true, uniqueness: true

  enum :device_type, { ios: 0, android: 1 }
  enum :locale, I18n.available_locales

  normalizes :email, with: ->(email) { email.strip.downcase }

  after_create_commit :send_welcome_notification

  def test_user?
    email == Rails.application.credentials.appstore_test_user_email
  end

  def active_tournament
    @active_tournament ||= tournament_participants.joins(:tournament).merge(Tournament.active).first&.tournament
  end

  def send_welcome_notification
    Notification.create(
      user: self,
      title: 'Welcome to StepStreak!',
      body: 'We hope you enjoy using the app. why dont you start by creating a goal or joining a challenge?'
    )
  end
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApplicationController
    def update
      if current_user.update(user_params)
        render plain: "OK"
      else
        render json: current_user.errors, status: :unprocessable_content
      end
    end

    private

    def user_params
      params.require(:user).permit(:device_type, :notification_token)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]
  before_action :set_user, only: [:edit, :update]
  before_action :redirect_if_authenticated, except: [:edit, :update, :destroy]
  before_action :check_if_test_user, only: [:destroy]

  def new
    @user = User.new
  end

  def create
    default_locale = cookies[:device_locale] || I18n.default_locale

    @user = User.create(user_params.merge(locale: default_locale))

    if @user.valid?
      sign_in @user

      redirect_path = if turbo_native_app? && app_version > '1.0'
                        permissions_path
                      else
                        root_path
                      end

      redirect_to redirect_path
    else
      flash[:alert] = @user.errors.full_messages.to_sentence
      render :new, status: :unprocessable_content
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to edit_user_path
    else
      flash[:alert] = @user.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_content
    end
  end

  def destroy
    if current_user.destroy
      redirect_to welcome_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation, :locale)
  end

  def set_user
    @user = current_user
  end

  def check_if_test_user
    if current_user.test_user?
      sign_out current_user

      redirect_to root_path
    end
  end
end

app/views/users/edit.html.erb
<% content_for :turbo_native_title, t('.page_title') %>

<div class="flex items-center p-4 mb-4 text-sm text-blue-800 rounded-lg bg-blue-50 dark:bg-gray-800 dark:text-blue-400" role="alert">
  <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
    <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
  </svg>
  <span class="sr-only">Info</span>
  <div>
    <%= t('.locale_change_note') %>
  </div>
</div>

<div class="flex min-h-full flex-col px-6 mx-auto md:h-screen turbo-native:h-screen dark:bg-gray-900 mt-10">
  <div class="w-full max-w-xl p-6 space-y-8 sm:p-8 bg-white rounded-lg shadow dark:bg-gray-800">
    <%= form_with model: @user, url: user_path(@user), html: { "data-turbo-action": "replace" }, class: "mt-8 space-y-6 turbo-native:mt-0" do |form| %>
      <%= render 'shared/flash_errors' %>

      <div>
        <%= form.label :locale, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
        <%= form.select :locale, User.locales.keys.map {|locale| [t(locale, scope: 'enums.user.locale'), locale]}, {}, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" %>
      </div>

      <%= form.submit t('save'), class: 'w-full px-5 py-3 text-base font-medium text-center text-white bg-primary-700 rounded-lg hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 sm:w-auto dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800' %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% content_for :turbo_native_title, t('.page_title') %>

<div class="flex min-h-full flex-col px-6 mx-auto md:h-screen turbo-native:h-screen dark:bg-gray-900 mt-10">
  <div class="w-full max-w-xl p-6 space-y-8 sm:p-8 bg-white rounded-lg shadow dark:bg-gray-800">
    <%= form_with model: @user, url: users_path, html: { "data-turbo-action": "replace" }, class: "mt-8 space-y-6 turbo-native:mt-0" do |form| %>
      <%= render 'shared/flash_errors' %>

      <div>
        <%= form.label :email, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
        <%= form.email_field :email, autocomplete: "email", required: true, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" %>
      </div>

      <div>
        <%= form.label :username, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
        <%= form.text_field :username, autocomplete: "username", required: true, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" %>
      </div>

      <div>
        <%= form.label :password, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
        <%= form.password_field :password, autocomplete: "password", required: true, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" %>
      </div>

      <div>
        <%= form.label :password_confirmation, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
        <%= form.password_field :password_confirmation, autocomplete: "password", required: true, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" %>
      </div>

      <%= form.submit t('.sign_up'), class: 'w-full px-5 py-3 text-base font-medium text-center text-white bg-primary-700 rounded-lg hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 sm:w-auto dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800' %>
    <% end %>
  </div>

  <div class="bottom-0 mt-5">
    <div class="flex items-center justify-center">
      <span class="font-medium dark:text-white"><%= t('.sign_in_instead') %></span>
      <%= link_to t('.sign_in'), new_session_path, class: 'long-press-disabled py-2 px-1 text-blue-700 dark:text-blue-400 font-bold rounded-full' %>
    </div>
  </div>
</div>